//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libConsPedidoMtto.refSvcPedidoMtto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsPedidoMtto", Namespace="http://schemas.datacontract.org/2004/07/wcfPedidoMtto")]
    [System.SerializableAttribute()]
    public partial class clsPedidoMtto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTecnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable DetalleProdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FuncionoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IvaOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorOrdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCliente {
            get {
                return this.CodClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodClienteField, value) != true)) {
                    this.CodClienteField = value;
                    this.RaisePropertyChanged("CodCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTecnico {
            get {
                return this.CodTecnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTecnicoField, value) != true)) {
                    this.CodTecnicoField = value;
                    this.RaisePropertyChanged("CodTecnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable DetalleProd {
            get {
                return this.DetalleProdField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleProdField, value) != true)) {
                    this.DetalleProdField = value;
                    this.RaisePropertyChanged("DetalleProd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaOrden {
            get {
                return this.FechaOrdenField;
            }
            set {
                if ((this.FechaOrdenField.Equals(value) != true)) {
                    this.FechaOrdenField = value;
                    this.RaisePropertyChanged("FechaOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Funciono {
            get {
                return this.FuncionoField;
            }
            set {
                if ((this.FuncionoField.Equals(value) != true)) {
                    this.FuncionoField = value;
                    this.RaisePropertyChanged("Funciono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IvaOrden {
            get {
                return this.IvaOrdenField;
            }
            set {
                if ((this.IvaOrdenField.Equals(value) != true)) {
                    this.IvaOrdenField = value;
                    this.RaisePropertyChanged("IvaOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroOrden {
            get {
                return this.NumeroOrdenField;
            }
            set {
                if ((this.NumeroOrdenField.Equals(value) != true)) {
                    this.NumeroOrdenField = value;
                    this.RaisePropertyChanged("NumeroOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorOrd {
            get {
                return this.ValorOrdField;
            }
            set {
                if ((this.ValorOrdField.Equals(value) != true)) {
                    this.ValorOrdField = value;
                    this.RaisePropertyChanged("ValorOrd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="refSvcPedidoMtto.IPedidoMtto")]
    public interface IPedidoMtto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoMtto/GrabarPedido", ReplyAction="http://tempuri.org/IPedidoMtto/GrabarPedidoResponse")]
        libConsPedidoMtto.refSvcPedidoMtto.clsPedidoMtto GrabarPedido(libConsPedidoMtto.refSvcPedidoMtto.clsPedidoMtto objPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoMtto/GrabarPedido", ReplyAction="http://tempuri.org/IPedidoMtto/GrabarPedidoResponse")]
        System.Threading.Tasks.Task<libConsPedidoMtto.refSvcPedidoMtto.clsPedidoMtto> GrabarPedidoAsync(libConsPedidoMtto.refSvcPedidoMtto.clsPedidoMtto objPedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoMttoChannel : libConsPedidoMtto.refSvcPedidoMtto.IPedidoMtto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoMttoClient : System.ServiceModel.ClientBase<libConsPedidoMtto.refSvcPedidoMtto.IPedidoMtto>, libConsPedidoMtto.refSvcPedidoMtto.IPedidoMtto {
        
        public PedidoMttoClient() {
        }
        
        public PedidoMttoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoMttoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoMttoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoMttoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public libConsPedidoMtto.refSvcPedidoMtto.clsPedidoMtto GrabarPedido(libConsPedidoMtto.refSvcPedidoMtto.clsPedidoMtto objPedido) {
            return base.Channel.GrabarPedido(objPedido);
        }
        
        public System.Threading.Tasks.Task<libConsPedidoMtto.refSvcPedidoMtto.clsPedidoMtto> GrabarPedidoAsync(libConsPedidoMtto.refSvcPedidoMtto.clsPedidoMtto objPedido) {
            return base.Channel.GrabarPedidoAsync(objPedido);
        }
    }
}
